name: Upload

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Upload to test store(component-child)
        uses: blocklet/action-workflow@v1
        with:
          skip-deps: false
          skip-bundle: false
          skip-upload: false
          skip-deploy: true
          skip-release: true
          skip-readme: true
          bundle-command: pnpm bundle
          working-directory: blocklets/component-call-child
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}

      - name: Upload to test store(component-root)
        uses: blocklet/action-workflow@v1
        with:
          skip-deps: false
          skip-bundle: false
          skip-upload: false
          skip-deploy: true
          skip-release: true
          skip-readme: true
          bundle-command: pnpm bundle
          working-directory: blocklets/component-call-root
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
